Repository SamarjeetBanik/get-your-PR-accepted, pull requests merged in 2021-10, with the labels that each got.

#7 Hello Hacktober
  Hello.java
Labels: hacktoberfest, hacktoberfest-accepeted

#5 Create Binary Search without Recursion in Python
  Sorting/Python/Binary Search without Recursion in Python
Labels: documentation, hacktoberfest

#8 Add Sudeep Gangwar to Contributers list
  Contributors.md
  Sorting/C++/BubbleSort.cpp
Labels: help wanted, good first issue, hacktoberfest

#6 Add Shravya to Contributors list
  Contributors.md
Labels: help wanted, good first issue, hacktoberfest

#15 Adding Implementation of Merge Sort in C++
  Sorting/C++/MergeSort.cpp
Labels: hacktoberfest

#12 Added NQueen problem of backtracking
  Backtracking Problems/Java/NQueen Problem.java
  Contributors.md
Labels: documentation, good first issue, hacktoberfest

#29 Update Contributors.md
  Contributors.md
Labels: good first issue, hacktoberfest, hacktoberfest-accepeted

#18 Adjacency list
  Graph Problems/C/Graph_AdjacencyList.c
  Graph Problems/C/Graph_AdjacencyMatrix.c
  HeapSort.c
  binarysearch.c
Labels: good first issue, hacktoberfest

#26 Create comb-sort.cpp
  Sorting/C++/CombSort.cpp
Labels: good first issue, hacktoberfest

#41 Solution of Longest Palindromic Subsequence - C++
  Dynamic Programming/C++/LongestPalindromicSubsequence.cpp
Labels: enhancement, good first issue, hacktoberfest

#36 Add Romil to Contributors List
  Contributors.md
Labels: enhancement, help wanted, good first issue, hacktoberfest

#43 Tree Traversal of BST
  BST/C++/TreeTraversalBST.cpp
Labels: good first issue, hacktoberfest

#52 Programme For CycleSort In C
  Sorting/C/CycleSort.c
Labels: enhancement, good first issue, hacktoberfest

#51 Heap Sort
  Contributors.md
  Sorting/Java/HeapSort.java
Labels: enhancement, good first issue, hacktoberfest

#82 timsort radixsort bucketsort heapsort added in c++ folder
  Sorting/C++/BucketSort.cpp
  Sorting/C++/HeapSort.cpp
  Sorting/C++/RadixSort.cpp
  Sorting/C++/Timsort.cpp
Labels: good first issue, hacktoberfest

#44 Create FindCycleInGraph.cpp
  Graph Problems/C++/FindCycleInGraph.cpp
Labels: enhancement, good first issue, hacktoberfest

#57 Cycle Sort using cpp
  Sorting/C++/CycleSort.cpp
Labels: enhancement, hacktoberfest

#64 add BinarySearch.cpp
  Contributors.md
  Searching/C++/BinarySearch.cpp
Labels: enhancement, good first issue, hacktoberfest

#69 linear_search in c
  Contributors.md
  Searching/C/LinearSearch.c
Labels: documentation, enhancement, good first issue, hacktoberfest

#89 Added Selection Sort
  Contributors.md
  Sorting/Contributors.md
  Sorting/Java/Selection Sort/SelectionSort.java
  Sorting/Java/Selection Sort/StableSelectionSort.java
Labels: enhancement, good first issue, hacktoberfest

#85 Added N-Queens Problem in Backtracking
  Backtracking Problems/C++/NQueens.cpp
  Contributors.md
Labels: documentation, enhancement, good first issue, hacktoberfest
